---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initcpiocfg
      - bootloader
      - packages
  - show:
      - finished
branding: zentrix
prompt-install: true
quit-at-end: false
